import { Roboto } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { Providers } from "./provider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "RDK dev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className + " bg-primary"}>
        <nav>
          <Header />
        </nav>

        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
