import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "RDK dev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className + " bg-primary"}>
        <nav>
          <Header />
        </nav>

        {children}
      </body>
    </html>
  );
}
