import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "RDK dev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className + " bg-primary"}>
        <div className="flex flex-col gap-[44px] text-white w-full">
          <nav>
            <Navbar />
          </nav>

          {children}
        </div>
      </body>
    </html>
  );
}
